### PR TITLE
Removed 8.0.3 from rhpam-config

### PR DESCRIPTION
**Pull request by akumar074**

### CODE REVIEW

**Comment by akumar074** [comment]
@mareknovotny @rgdoliveira `ci/prow/config` - failure doesn't seem expected in this case as we are removing 8.0.3 configs, and we are not making any change in current version 8.0.5
```
{  ./hack/go-configs.sh
From https://github.com/kiegroup/kie-cloud-operator
 * branch            dfd534b46f9524e170f2a585187bef9b10d4f4ba -> FETCH_HEAD
Detected changes to an older version's config file(s). Current version changes are only allowed in rhpam-config/8.0.5.
Undo changes to the following files -
rhpam-config/8.0.3/common.yaml
rhpam-config/8.0.3/dashbuilder/rhpam-standalone-dashbuilder.yaml
rhpam-config/8.0.3/dbs/mysql.yaml
rhpam-config/8.0.3/dbs/pim/external.yaml
rhpam-config/8.0.3/dbs/pim/mysql.yaml
rhpam-config/8.0.3/dbs/pim/postgresql.yaml
rhpam-config/8.0.3/dbs/postgresql.yaml
rhpam-config/8.0.3/dbs/servers/external.yaml
rhpam-config/8.0.3/dbs/servers/h2.yaml
rhpam-config/8.0.3/dbs/servers/mysql.yaml
rhpam-config/8.0.3/dbs/servers/postgresql.yaml
rhpam-config/8.0.3/envs/rhdm-authoring-ha.yaml
rhpam-config/8.0.3/envs/rhdm-authoring.yaml
rhpam-config/8.0.3/envs/rhdm-production-immutable.yaml
rhpam-config/8.0.3/envs/rhdm-trial.yaml
rhpam-config/8.0.3/envs/rhpam-authoring-ha.yaml
rhpam-config/8.0.3/envs/rhpam-authoring.yaml
rhpam-config/8.0.3/envs/rhpam-production-immutable.yaml
rhpam-config/8.0.3/envs/rhpam-production.yaml
rhpam-config/8.0.3/envs/rhpam-standalone-dashbuilder.yaml
rhpam-config/8.0.3/envs/rhpam-trial.yaml
rhpam-config/8.0.3/jms/activemq-jms-config.yaml
rhpam-config/8.0.3/pim/process-migration.yaml
make: *** [check-configs] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-03-28T15:02:54Z"}
}
```

**Comment by spolti** [comment]
when removing old config files, this error is expected.

**Comment by rgdoliveira** [comment]
`ci/prow/unit` is green now, the PR looks good to me

**Review by rgdoliveira — APPROVED** [review]

**Comment by spolti** [comment]
btw, it needs to be merged manually :)

**Pull request merged**
