### PR TITLE
[RHPAM-2503]- Console UI - Support for mounting roleMapping and GitHooks

### PR DESCRIPTION
**Pull request by swati-kale**
[RHPAM-2175] Remove controllerUser and executionUser

Signed-off-by: Swati Kale <swkale@redhat.com>

### CODE REVIEW

**Comment by tchughesiv** [comment]
@ruromero @swati-kale can someone explain difference between this PR and the one already submitted?
https://github.com/kiegroup/kie-cloud-operator/pull/305

**Comment by swati-kale** [comment]
> @ruromero @swati-kale can someone explain difference between this PR and the one already submitted?
> #305

**Comment by swati-kale** [comment]
> > @ruromero @swati-kale can someone explain difference between this PR and the one already submitted?




> @ruromero @swati-kale can someone explain difference between this PR and the one already submitted?
> #305

The earlier was operator side changes, there are some corresponding form.json changes at UI side.

**Comment by tchughesiv** [comment]
please rebase

**Comment by swati-kale** [comment]
@tchughesiv , did rebase.

**Pull request merged**
