### PR TITLE
check for openshift cluster before watching objects

### PR DESCRIPTION
**Pull request by tchughesiv**
/assign @bmozaffa @sutaakar 

Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
@sutaakar FYI, this is part of an attempt to reuse common operator code across all of middleware (if not more). The starting point here, which is fairly trivial, is that we don't run on pure k8s and many other operators also need to know if running on ocp or k8s

**Comment by sutaakar** [comment]
ok

**Pull request merged**
