### PR TITLE
Cleanup and remove dead code

### PR DESCRIPTION
**Pull request by ruromero**
* Remove dead code
* Add comments
* Fixed few typos
* Refactored `EnvVarCheck` method and created unit test
* Renamed `KieAppReconciler` to `Reconciler` as per go-lint suggestion
* Added Apache 2.0 license
* Added go-report badge

### CODE REVIEW

**Comment by ruromero** [comment]
[Operator: Remove dead code](https://trello.com/c/PEuI4tBz/114-operator-remove-dead-code)

**Comment by bmozaffa** [comment]
> I think @bmozaffa wanted to keep as `KieAppReconciler` ... will let him weigh in.

No, it's fine by me.

**Pull request merged**
