### PR TITLE
update OWNERS file

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as members of the kiegroup org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * vaibhavjainwiz
>   
>   * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

@mareknovotny can you please help us with this issue?
Looks like Vaibhav is not member of kiegroup org.

**Comment by mareknovotny** [comment]
i will add him if he is missing in kiegroup

**Comment by spolti** [comment]
@tchughesiv any idea about what can be missing?

**Comment by tchughesiv** [comment]
idk, can you tell what differences there might be between desmax74 and vaibhavjainwiz with regards to this repo and org?

**Comment by spolti** [comment]
both are on the same team on the org.

**Comment by spolti** [comment]
maybe Vaibhav needs at least one contribution?

**Comment by mareknovotny** [comment]
@spolti @tchughesiv i can see only one difference and that is the **Public** vs **Private** member of kiegroup org with comparing **desmax74** and **vaibhavjainwiz**. I will try to switch it to Public for **vaibhavjainwiz** too and will run the verification here.

**Comment by mareknovotny** [comment]
so i checked the github documentation and @vaibhavjainwiz needs to switch the public visibilit himself see https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership

**Comment by vaibhavjainwiz** [comment]
@mareknovotny I changed my visiblity to public by following link which you have attached above. Could you please check now.

**Comment by spolti** [comment]
cool, thanks.

**Comment by spolti** [comment]
ok, let me cherry-pick it.

**Comment by spolti** [comment]
done https://github.com/kiegroup/kie-cloud-operator/pull/636

**Pull request merged**
