### PR TITLE
[RHPAM-4109] Cannot open created project - FileSystem Index fails - Nullpointer

### PR DESCRIPTION
**Pull request by desmax74**
See: https://issues.redhat.com/browse/RHPAM-4109

Signed-off-by: desmax74 <mdessi@redhat.com>

### CODE REVIEW

**Comment by desmax74** [comment]
@jakubschwan @spolti @tomasdavidorg

**Review by tomasdavidorg — APPROVED** [review]

**Review by jakubschwan — APPROVED** [review]
lgtm

**Pull request merged**
