### PR TITLE
[RHPAM-2205] - Add AMQ support to Operator installer UI

### PR DESCRIPTION
**Pull request by swati-kale**
Signed-off-by: Swati Kale <swkale@redhat.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
@swati-kale please remove the release target from the PR title... we have other ways of correlating that information and hardcoding it in the PR risks falling out of sync

**Comment by swati-kale** [comment]
> @swati-kale please remove the release target from the PR title... we have other ways of correlating that information and hardcoding it in the PR risks falling out of sync

ok, updated the title.

**Pull request merged**
