### PR TITLE
[RHPAM-2694] Create ServiceMonitor for operator metrics

### PR DESCRIPTION
**Pull request by bmozaffa**
Create ServiceMonitor pointing to the metrics service.

Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>

### CODE REVIEW

**Comment by ruromero** [comment]
For reference https://github.com/operator-framework/operator-sdk/blob/master/doc/user/metrics/service-monitor.md
/lgtm

**Comment by bmozaffa** [comment]
This is now validated to work OOTB in OCP 4.3 user workload monitoring

**Comment by tchughesiv** [comment]
please rebase

**Comment by bmozaffa** [comment]
@tchughesiv this is just waiting for an lgtm

**Pull request merged**
