### PR TITLE
[RHPAM-2209] Allow configure GitHooks and RoleMapper

### PR DESCRIPTION
**Pull request by ruromero**
Fix https://issues.jboss.org/browse/RHPAM-2209

* Allows using pre-existing resources to mount the GitHooks folders to the Console and/or the RoleMapper file to both the Console and any KieServer set.
* If the external resource does not exist or cannot be accessed, the deployment will fail.
* The supported types are `ConfigMap`, `Secret` and `PersistentVolumeClaim`

Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

### CODE REVIEW

**Comment by tchughesiv** [comment]
@ruromero please rebase and move the changes to 7.6.0 config files now in master branch

**Comment by ruromero** [comment]
/hold cancel
@tchughesiv done

**Pull request merged**
