### PR TITLE
[RHPAM-3541] - Rectified different default request values in Template…

### PR DESCRIPTION
**Pull request by amadhusu**
[RHPAM-3541] - Rectified different default request values in Templates and Operator
https://issues.redhat.com/browse/RHPAM-3541

Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: [RHDM-XYZ] Subject
- [x]  Pull Request contains link to the JIRA issue
- [x]  Pull Request contains description of the issue
- [x]  Pull Request does not include fixes for issues other than the main ticket
- [x]  Attached commits represent units of work and are properly formatted
- [x]  You have read and agreed to the Developer Certificate of Origin (DCO) (see CONTRIBUTING.md)
- [x]  Every commit contains Signed-off-by: Your Name yourname@example.com - use git commit -s

### CODE REVIEW

**Review by spolti — CHANGES_REQUESTED** [review]

**Comment by spolti** [comment]
one tip, when you don't update the crd, just make test is enough.
Also, please add tests to check the new default values and custom ones.

**Comment by amadhusu** [comment]
Closing this PR as there is a new PR created - https://github.com/kiegroup/kie-cloud-operator/pull/699 rather than rebasing the same.

**Pull request closed without merging**
