### PR TITLE
[KIECLOUD-217] - Kie data path standardization

### PR DESCRIPTION
**Pull request by ricardozanini**
Please:
https://issues.jboss.org/browse/KIECLOUD-217

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
/lgtm

Please let me or @tchughesiv know when the image PRs have been merged, and a new image build is available before we merge this.

**Comment by ricardozanini** [comment]
@bmozaffa I beg your pardon, but could you please reformulate? I didn't understand your request.

**Comment by bmozaffa** [comment]
@ricardozanini I assume that if I were to build the operator image and try to run/test it right now with your PR, it would break things, given that the KIE server image I use does not have your PR merged. I meant that we should probably wait till your other PRs are merged and a nightly / dev build of KIE server image is available to verify this with the operator and merge this one.

**Comment by ricardozanini** [comment]
@bmozaffa got it now. You don't need to worry about a new version of the image built, since this PR won't depend on it. It should work fine with the currently image builds. But, yeah please wait to merge it until we are all done on the templates side.

**Comment by errantepiphany** [comment]
@bmozaffa , @ricardozanini The templates, scripts, and abp changes have all been merged. Once this operator PR is merged, we can close the KIECLOUD-217 jira.

**Pull request merged**
