### PR TITLE
[KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…

### PR DESCRIPTION
**Pull request by Kaitou786**
…t causing POD Termination

See: https://issues.redhat.com/browse/KIECLOUD-438

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@Kaitou786 I think it needs to be cherry picked to master, right @tchughesiv ?

**Comment by sutaakar** [comment]
This change causes **minimal** Business central startup time to be 3 minutes. That is unnecessary for fast environments with trial environment.
IMHO the probes deserve complex adjustments as IMHO with the startup probe the liveness probe doesn't need `initialDelaySeconds`, also thresholds could be adjusted.

**Pull request merged**
