### PR TITLE
[KIECLOUD-656] - Prepare RHPAM branches for 7.13.2

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by rgdoliveira** [comment]
@spolti shouldn't this PR be opened against release-v7.13.x branch instead of main? Or you will backport it later?

**Comment by spolti** [comment]
> @spolti shouldn't this PR be opened against release-v7.13.x branch instead of main? Or you will backport it later?

no, main is 7.13.2.

**Comment by spolti** [comment]
> > > @spolti shouldn't this PR be opened against release-v7.13.x branch instead of main? Or you will backport it later?
> > 
> > 
> > no, main is 7.13.2.
> 
> I'm confused, when we build the BA operator we checkout to branch `release-v7.13.x`, isn't it @lampajr ?

yes, 7.13.x is pointing to 7.13.1-2 atm.

**Review by rgdoliveira — APPROVED** [review]

**Comment by rgdoliveira** [comment]
> > > > @spolti shouldn't this PR be opened against release-v7.13.x branch instead of main? Or you will backport it later?
> > > 
> > > 
> > > no, main is 7.13.2.
> > 
> > 
> > I'm confused, when we build the BA operator we checkout to branch `release-v7.13.x`, isn't it @lampajr ?
> 
> yes, 7.13.x is pointing to 7.13.1-2 atm.

I see, so for release-v7.13.x branch you will add the 7.13.2-1 OLM, right?

**Pull request merged**
