### PR TITLE
[KIECLOUD-231] watch/reconcile UI objects

### PR DESCRIPTION
**Pull request by tchughesiv**
/assign @bmozaffa 

Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
@sutaakar this is against master, so not necessarily cherry-picked for 7.4.0, but we can apply it against 7.4.0 as well if you think appropriate. Your call!

**Comment by sutaakar** [comment]
it is ok to keep it just on master, not a critical issue

**Pull request merged**
