### PR TITLE
[RHPAM-3279] Configure CORS automatically through a flag or environment variable

### PR DESCRIPTION
**Pull request by desmax74**
Version with one checkbox to use default values
See: https://issues.redhat.com/browse/RHPAM-3279
7.12.0

### CODE REVIEW

**Comment by spolti** [comment]
15k additions, is it correct?

**Comment by spolti** [comment]
it doesn't sounds right to me, these commits shouldn't be here, it might worth apply your changes on a clean PR based on main?

**Comment by desmax74** [comment]
Replaced by https://github.com/kiegroup/kie-cloud-operator/pull/669

**Pull request closed without merging**
