### PR TITLE
[RHPAM-2401-1] - QE review, db is not ba component

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by tchughesiv** [comment]
@spolti is this targeted for 7.6.0 also? if so, maybe start with a PR against `release-1.3.x` branch... then cherry pick to master and add 7.6.1 change?

**Comment by spolti** [comment]
Yes, I'll, didn't have time to do both before meetings && lunch. doing now.

**Comment by spolti** [comment]
done
https://github.com/kiegroup/kie-cloud-operator/pull/329

**Pull request merged**
