### PR TITLE
[RHPAM-3326] - Defaul value for MaxMetaspaceSize in Operator overried…

### PR DESCRIPTION
**Pull request by Kaitou786**
…s default values set by image scripts
Default values added in the respective images and remove from the operator
See: https://issues.redhat.com/browse/RHPAM-3326

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@Kaitou786 is this issue ready to be merged?

**Comment by Kaitou786** [comment]
> @Kaitou786 is this issue ready to be merged?

Yes :D

**Review by tchughesiv — CHANGES_REQUESTED** [review]
can you add a unit test for this?

**Review by tchughesiv — APPROVED** [review]

**Pull request merged**
