### PR TITLE
[KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…

### PR DESCRIPTION
**Pull request by Kaitou786**
…t causing POD Termination

See: https://issues.redhat.com/browse/KIECLOUD-438
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

### CODE REVIEW

**Comment by Kaitou786** [comment]
@tchughesiv does this needs to be cherry-picked to the `release-v7.9.x` branch. Since this is targeted for 7.9.1 release ?

**Comment by tchughesiv** [comment]
> @tchughesiv does this needs to be cherry-picked to the `release-v7.9.x` branch. Since this is targeted for 7.9.1 release ?

correct

**Comment by Kaitou786** [comment]
@tchughesiv [cherrypick](https://github.com/kiegroup/kie-cloud-operator/pull/557)

**Pull request merged**
