### PR TITLE
[KIECLOUD-89] Log messages should be in lowercase. Refactor pwd gener…

### PR DESCRIPTION
**Pull request by ruromero**
* Log messages in Go should start with lower case
* Password generation logic extracted to a new function to reduce duplicity

Fix https://issues.jboss.org/browse/KIECLOUD-89

Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

### CODE REVIEW

**Comment by tchughesiv** [comment]
@ruromero do we have a test that checks if the operator keeps a password that is already set. if not, can you add one? otherwise LGTM.

**Comment by ruromero** [comment]
@tchughesiv these 2 tests should be covering that part https://github.com/kiegroup/kie-cloud-operator/blob/1204e124045ef4a907c1b0b5c590973e97718169/pkg/controller/kieapp/defaults/defaults_test.go#L330-L379

**Comment by bmozaffa** [comment]
> * Log messages in Go should start with lower case

Source / reference for this rule/convention?

**Comment by ruromero** [comment]
It seems it only applies to error messages
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

**Comment by ruromero** [comment]
@bmozaffa done

**Pull request merged**
