### PR TITLE
increment version 1.0.1 for 7.3.1

### PR DESCRIPTION
**Pull request by tchughesiv**
/assign @bmozaffa 

 - improved handling of source code artifact

bring up master to 1.0.1 / 7.3.1 to match `1.0.x` branch before versioning for 1.1 / 7.4 in master.
i should have done this to master first originally and cherry-picked to 1.0.x ... will do next time.

Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by tchughesiv** [comment]
/hold
@bmozaffa can i cherry-pick from 1.0.x instead? i may attempt that first

**Comment by bmozaffa** [comment]
That's awesome!

/lgtm

**Pull request merged**
