### PR TITLE
[KIECLOUD-328] required changes to build meta information for CPaaS

### PR DESCRIPTION
**Pull request by errantepiphany**
[KIECLOUD-328] required changes to build meta information for CPaaS
https://issues.jboss.org/browse/KIECLOUD-328

Signed-off-by: David Ward <dward@redhat.com>

### CODE REVIEW

**Comment by errantepiphany** [comment]
Please do not merge, as this needs to be verified.
This PR is intended for the 7.5.0 release.

**Comment by tchughesiv** [comment]
@errantepiphany i assume this will also need to be cherry-picked to release-1.2.x branch for `7.5.0` release?

**Comment by errantepiphany** [comment]
@tchughesiv Honestly I didn't know which branch the 7.5.0 work should go against. Thus, I will close this PR and open another against that branch. It was a bit confusing for me since the branch naming convention in our other github repos is a bit easier to understand: 7.4.x, 7.5.x, master for the _next_ version (7.6)...

**Comment by tchughesiv** [comment]
@errantepiphany the PR against master is valid as master has 7.5.1 currently... it will also need to be cherry-picked to `release-1.2.x`

**Comment by errantepiphany** [comment]
@tchughesiv But that's what this one is intended for: https://github.com/kiegroup/kie-cloud-operator/pull/273

**Comment by tchughesiv** [comment]
> @tchughesiv But that's what this one is intended for: #273

@errantepiphany that PR appears to be for 7.6.x

**Comment by errantepiphany** [comment]
@tchughesiv Yeah, I'm closing everything and starting over, given our gchat conversation.

**Pull request closed without merging**
