### PR TITLE
Refactor to use new operator-utils functions

### PR DESCRIPTION
**Pull request by bmozaffa**
Use new write library from operator-utils
Conform to other refactors in operator-utils library

Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
@tchughesiv this is ready for merge after you get a chance to review. There should be no functional changes.

**Comment by tchughesiv** [comment]
/hold
until master is at 7.6 / 1.3 codebase

**Pull request merged**
