### PR TITLE
[RHPAM-3763] - Endless updating loop in Kie operator

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@tchughesiv hey, just to confirm, there is no need to cherry pick for 7.11.1, as before release we merge everything that is on main onto 7.11.x branch, right?

**Comment by tchughesiv** [comment]
idk @spolti ... looks like the wrong line is still in 7.11.x and main branches...

https://github.com/kiegroup/kie-cloud-operator/blob/release-v7.11.x/pkg/controller/kieapp/deploy_ui.go#L62
https://github.com/kiegroup/kie-cloud-operator/blob/main/pkg/controller/kieapp/deploy_ui.go#L62

**Comment by tchughesiv** [comment]
/lgtm
I think this needs to happen in the other 2 branches as well

**Comment by spolti** [comment]
ok, thanks.

**Pull request merged**
