### PR TITLE
[release-v7.13.x-blue-next][RHPAM-4904] Add required annotations for Infrastructure Feature Test

### PR DESCRIPTION
**Pull request by akumar074**
Related PRs : https://github.com/kiegroup/kogito-operator/pull/23

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]
/approve

**Comment by mareknovotny** [comment]
there are just format errors, please check what @rgdoliveira did to fix them at https://github.com/kiegroup/kie-cloud-operator/commit/a48a0d126691f45621ef348c53b20ee68d18efb0

**Comment by rgdoliveira** [comment]
@akumar074 I guess the easier way for you to fix the failure in ci/prow/format is running `./hack/go-fmt.sh` script inside the operator repo. I run it and it showed a diff on file `pkg/apis/app/v2/zz_generated.deepcopy.go`, I believe you have to commit that diff too. 

It seems as part of previous PR `Bump BAMOE version in the next branch` this file was modified and maybe also the ci/prow/format failed before.

**Review by rgdoliveira — APPROVED** [review]

**Comment by akumar074** [comment]
Hello @jakubschwan, Kindly provide your review on this PR and merge if it looks good.

**Comment by rgdoliveira** [comment]
@mareknovotny @akumar074 Just one thing, I believe `ci/prow/unit` should not fail, at least it was not before https://github.com/kiegroup/kie-cloud-operator/pull/943 was merged. 

I would guess something may be missing to be updated? Sorry I'm no expert in this repo but if you need help I can try to investigate.

**Comment by rgdoliveira** [comment]
we discussed on channel what might be the reason of ci/prow/unit failing. So let's merge this one as it is and create a new PR trying to fix the test failure.

**Pull request merged**
