### PR TITLE
[RHPAM-2803] add image digests for 7.7.0 release & remove PIM images

### PR DESCRIPTION
**Pull request by tchughesiv**
cherry-picking what was already pushed to release-v1.4.x branch.

/assign @bmozaffa 

Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by ruromero** [comment]
Why removing PIM images? Aren't we going to have it full support in 7.8.0?

**Comment by tchughesiv** [comment]
> Why removing PIM images? Aren't we going to have it full support in 7.8.0?
This is a cherry-pick of a necessary `7.7.0` change (https://github.com/kiegroup/kie-cloud-operator/pull/395) given that pim images do not exist yet, nor does PIM functionality in the operator. Having PIM listed as a 7.7.0 image in relatedImages, will break disonnected install... hence the removal for now.

IMO, this image addition should instead be added to the PIM PR which has yet to merge - https://github.com/kiegroup/kie-cloud-operator/pull/324

**Comment by ruromero** [comment]
@xiezhang7 do you mind adding this change to your PR #324  ?

**Comment by tchughesiv** [comment]
@xiezhang7 don't cherry-pick https://github.com/kiegroup/kie-cloud-operator/pull/324 though.

all you should have to do is uncomment these lines and run `make csv` in your branch.
https://github.com/kiegroup/kie-cloud-operator/blob/58a7deb9a7534475b534e5b2147723432a1f863a/pkg/controller/kieapp/constants/constants.go#L166-L172

**Comment by xiezhang7** [comment]
@ruromero @tchughesiv sure, I'll do it when working on supporting external DB.

**Comment by tchughesiv** [comment]
> @ruromero @tchughesiv sure, I'll do it when working on supporting external DB.

@xiezhang7 is that in this PR? Cause it should be done in this PR.
https://github.com/kiegroup/kie-cloud-operator/pull/324

**Comment by xiezhang7** [comment]
> @xiezhang7 is that in this PR? Cause it should be done in this PR.
> #324

Yes, supporing external DB is supposed to be done in #324 . But I haven't started yet.

**Pull request merged**
