### PR TITLE
[KIECLOUD-46] Refactor processing of OpenShift objects

### PR DESCRIPTION
**Pull request by bmozaffa**
Refactor code to remove repeating blocks, and also to bubble up potential errors

Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
@tchughesiv Please review! I've verified creating the production env with this.

**Comment by tchughesiv** [comment]
@bmozaffa looks good but there's still a sporadic issue deploying envs w/ this codebase... specifically around route creation. I see the following errors sporadically, regardless of env:
```shell
INFO[0046] Creating a new Route tommy3/trial-rhpamcentr 
INFO[0046] Failed to create new Route tommy3/trial-rhpamcentr: services "trial-rhpamcentr" already exists 

INFO[0538] Creating a new Route tommy3/authoring-ha-kieserver-0 
INFO[0538] Failed to create new Route tommy3/authoring-ha-kieserver-0: services "authoring-ha-kieserver-0" already exists 

INFO[0635] Creating a new Route tommy3/production-smartrouter 
INFO[0635] Failed to create new Route tommy3/production-smartrouter: services "production-smartrouter" already exists 
```
The critical route(s) then do not exist post deployment.

**Comment by tchughesiv** [comment]
@bmozaffa fix is here... let me know if you want a PR from me or just want to modify your code directly:
https://github.com/tchughesiv/kie-cloud-operator/commit/7f4118fb7b49fb160ec92bc377b255d90cb13f0a

the route specific fix is here:
https://github.com/tchughesiv/kie-cloud-operator/commit/7f4118fb7b49fb160ec92bc377b255d90cb13f0a#diff-9ecb910ca7304714ab23ba15d8cf55a5R426

**Comment by bmozaffa** [comment]
> @bmozaffa fix is here... let me know if you want a PR from me or just want to modify your code directly:
> [tchughesiv@7f4118f](https://github.com/tchughesiv/kie-cloud-operator/commit/7f4118fb7b49fb160ec92bc377b255d90cb13f0a)
> 
> the route specific fix is here:
> [tchughesiv@7f4118f#diff-9ecb910ca7304714ab23ba15d8cf55a5R426](https://github.com/tchughesiv/kie-cloud-operator/commit/7f4118fb7b49fb160ec92bc377b255d90cb13f0a#diff-9ecb910ca7304714ab23ba15d8cf55a5R426)

Ah, thanks @tchughesiv , I was worried I'd end up with a bug like that and I still did. Please take a last look before I merge.

**Comment by tchughesiv** [comment]
@bmozaffa LGTM

**Pull request merged**
