### PR TITLE
[RHPAM-2684] Upgrade to ocp43 and latest operator-utils

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

Upgrade dependencies to:

- kubernetes-1.16.2
- Operator Framework v0.14.1
- OpenShift 4.3
- operator-utils k8s1.16_ocp4.3

### CODE REVIEW

**Comment by ruromero** [comment]
This is what I´m doing https://github.com/kiegroup/kie-cloud-operator/pull/386/files#diff-7afe105b088dba0b3d99b65fe12546ddL577

**Comment by bmozaffa** [comment]
@ruromero sorry, I missed that... so why is the implementation of the interface not in operator-utils?

**Comment by ruromero** [comment]
Isn't it there already?
https://github.com/kiegroup/kie-cloud-operator/pull/386/files?file-filters%5B%5D=.go#diff-407a5efa6652178a5c97a002aa1bb12dL13

**Comment by bmozaffa** [comment]
Weird, never mind me! Must have been looking at the wrong branch.

**Comment by tchughesiv** [comment]
please rebase

**Pull request merged**
