### PR TITLE
Full reconcile of resources using shared library

### PR DESCRIPTION
**Pull request by bmozaffa**
Use new operator-utils functionality to do a full reconcile of requested and existing resources

Remaining items:
- Pass unit tests
- Refactor route hostname so update happens automatically as hostname is set

### CODE REVIEW

**Comment by bmozaffa** [comment]
@jeremyary Also see this one

**Comment by bmozaffa** [comment]
@tchughesiv issues should be resolved now, please review and test again.

**Comment by tchughesiv** [comment]
@bmozaffa updates are working again. 

we still have an issue, however, with the provisioning loop and it appears to be related (at least in part) to imagestream triggers. for example, here's a diff between the same DC in openshift as it continually reconciles.

```bash
$ diff dc1.yaml dc2.yaml 
5c5
<   generation: 67
---
>   generation: 68
20c20
<   resourceVersion: "1903219"
---
>   resourceVersion: "1903226"
143c143
<         image: rhpam74-kieserver-openshift:1.1
---
>         image: image-registry.openshift-image-registry.svc:5000/reconcile/rhpam74-kieserver-openshift@sha256:309ac7e6a56e4f7c6a1b4c87325fdac2ffc28c5aa4cacd53c755307065262ac5
232a233
>       lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/reconcile/rhpam74-kieserver-openshift@sha256:309ac7e6a56e4f7c6a1b4c87325fdac2ffc28c5aa4cacd53c755307065262ac5
261a263
> 
```

historically, we've only done comparisons of certain DC/BC fields/structs for this reason ... e.g. -
https://github.com/kiegroup/kie-cloud-operator/blob/1b0f9686dcf209034e7304e01ed38a1822165a65/pkg/controller/kieapp/kieapp_controller.go#L356-L423

**Comment by bmozaffa** [comment]
@tchughesiv all fields are not being compared. Fields like generation and resourceVersion are part of ObjectMeta and not Spec, and are [not included](https://github.com/RHsyseng/operator-utils/blob/master/pkg/resource/compare/defaults.go#L157-L162) in the comparison.

**Comment by bmozaffa** [comment]
@tchughesiv My 1.2 image in quay is the latest code, and there is no update to BC for rhdm immutable now.

**Pull request merged**
