### PR TITLE
[WIP] [RHPAM-2658] remove specDescripter value, add default to crd

### PR DESCRIPTION
**Pull request by tchughesiv**
/assign @ruromero @bmozaffa 

These changes reflect how @madorn says we should approach this going forward. 
https://github.com/kiegroup/kie-cloud-operator/pull/351#issuecomment-582707790

Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by tchughesiv** [comment]
Unsure how to proceed at this point @madorn @bmozaffa .
We require `apiextensions.k8s.io/v1` for the CRD in order to apply defaults, but we are currently pinned to k8s 1.14. v1 of apiextensions is not available until k8s 1.16.

This will likely have to wait until we can update the sdk to v0.13.x or higher.

**Comment by madorn** [comment]
@tchughesiv - understood. I suggest removing specDescriptors.value and placing desired defaults in CR example found within `alm-examples` section of the `ClusterServiceVersion`.

**Comment by bmozaffa** [comment]
or we could set the defaults in code as we do for some others, at least pending the upgrade?

**Comment by tchughesiv** [comment]
@bmozaffa i just tested and we already set them to false in the code by default. the issue is that the console will show as true unless we set the value in csv specDescriptor ... right @madorn ?
https://github.com/kiegroup/kie-cloud-operator/blob/97ce91c7727ed28bc00ef0488526e08e50090b17/pkg/apis/app/v2/kieapp_types.go#L115-L118

**Comment by tchughesiv** [comment]
closing in favor of https://github.com/kiegroup/kie-cloud-operator/pull/358

**Pull request closed without merging**
