### PR TITLE
Update RHPAM bundle for CVE respin

### PR DESCRIPTION
**Pull request by rgdoliveira**
Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/922
- https://github.com/kiegroup/kie-cloud-operator/pull/923

### CODE REVIEW

**Review by spolti — CHANGES_REQUESTED** [review]
something is not correct, the crd shouldn't be outside the tag directory, e.g. prod/manifest, it should be at 7.13.5-1/manifest.

**Comment by rgdoliveira** [comment]
> something is not correct, the crd shouldn't be outside the tag directory, e.g. prod/manifest, it should be at 7.13.5-1/manifest.

@spolti I've removed the files that were wrongly added outside a tag directory

**Review by spolti — COMMENTED** [review]
The 7.13.5-1 still missing the crd.

**Comment by rgdoliveira** [comment]
> The 7.13.5-1 still missing the crd.

the crd file for 7.13.5-1 is already there, see https://github.com/kiegroup/kie-cloud-operator/tree/main/deploy/olm-catalog/prod/7.13.5-1/manifests

@spolti you created the 7.13.5-1 before when you created the PRs to prepare for next branch, what I did on my PR was just to update the replaces of 7.13.5-1 to 7.13.4-2, instead of 7.13.4-1

**Review by spolti — APPROVED** [review]

**Pull request merged**
